### ISSUE TITLE
Re issue 24, links still redirecting to classic.

### ISSUE THREAD

**Issue by davidGravityLab** [dannysummerlin/force-navigator#28]
Still getting the classic links, particularly on the flow screen. The current link to flow is :
https://x.lightning.force.com/300?setupid=InteractionProcesses&retURL=%2Fui%2Fsetup%2FSetup%3Fsetupid%3DWorkflow

Should be something like https://x.sandbox.lightning.force.com/one/one.app#/setup/Flows/home

On version 3.2.13.

**Comment by benji1304** [comment]
I'm getting this again too. It seemed to be OK but now it's doing it again? 

@dannysummerlin were there any new changes?

**Comment by DavF27** [comment]
Hello, 

I have the same problem. If I want to go to any setup page it will redirect me in classic. 

My version is 3.2.13. 

Thanks,

**Comment by dannysummerlinjstartorg** [comment]
Hey all, thanks for keeping this on the radar. I have just pushed a minor update (3.2.25) for Chrome and Firefox. It seems like at some point in all its redirecting Lightning often would skip through a Classic page that led to the extension thinking it was in Classic (maybe a non-obvious frame on the page or something) and muck up the link map. I added a more direct Lightning check, so it should stay until you manually use the Toggle Lightning command. Please let me know after the update goes through if you continue to run into issues!

**Comment by benji1304** [comment]
Looking good so far! Thanks @dannysummerlin

**Comment by benji1304** [comment]
Worked fine on Monday but suddenly i'm getting classic pages again! Mostly with the flow page, that's the link I most commonly navigate to!

**Comment by DavidSmithnz** [comment]
I'm still seeing this error, I'm on version 3.2.25. I normally get this
error when going to Flows.

**Comment by dannysummerlinjstartorg** [comment]
This is the wildest damn thing - I have tried to preserve the mode several different ways, but for some reason things keep slipping through even when I have explicit checking. I'm continuing to work on it, worst case scenario I can match on the URL at the last moment, but that will only be good for as many as I make explicit and won't be future proof. Buuut I may have to go that way anyways.

**Comment by benji1304** [comment]
@dannysummerlin  did you manage to work this out ?

**Comment by dannysummerlin** [comment]
Hey y'all,

I am still working on it - you can see some progress here: https://github.com/dannysummerlin/force-navigator/tree/experiment-arrow -- the short of it is I redid a bunch of the guts and have it more explicitly populating the setup menus. It is working well, but a side consequence is that some of the other features need to be updated a bit, so I'm close but not quite there. Feel free to keep kicking me so I don't forget!

**Comment by benji1304** [comment]
happy to keep nudging you :D

**Comment by benji1304** [comment]
@dannysummerlin any updates?

**Comment by dannysummerlinjstartorg** [comment]
@benji1304 thank you for staying after me - I made a bunch of progress months ago, then got pulled a million ways, but I bore down on it today and the big update should be in the extension store soon! 4.1.2 will be the new version, a near total rewrite so hopefully I squashed all the current bugs, but I'm expecting y'all to find new ones so let me know in a new issue when/if those come up!
